### ISSUE TITLE
+[__NSPlaceholderDate initialize] causes Python to crash

### ISSUE THREAD

**Issue by AlessioZoccoli** [taspinar/twitterscraper#102]
**OS/ENVIRONMENT**
MacOs High Sierra v 10.13.2
Python 3.6.4
twitterscraper 0.6.0

**SUMMARY**
When I try to a query ( with query_tweets() ) I get the following error:

objc[2451]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[2451]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[2450]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[2450]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[2453]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[2453]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[2452]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[2452]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**CODE**

`
for tweet,i in zip(query_tweets(queryString, limit = 500, begindate = dt.date(2018,3,1), enddate = dt.date.today(), poolsize=4, lang='en'), range(0,500)):`
`
    int2tweet = {i: json_util.loads(tweet.encode('utf-8)}
`
`
    oscar2018.insert_one(int2tweet)
`

where queryString is just the OR statement and oscar2018 a mongo collection

Rusult doesn't change for any value of poolsize or limit

**Comment by taspinar** [comment]
It seems that this results from the specific Python version which is being used in MacOS 10.13 High Sierra.

According to [mikedlr](https://github.com/ansible/ansible/issues/34056#issuecomment-355994083) this should be fixed by taking the latest Python version from python.org. 

If this does not fix the problem, you could try to set the environment variable
`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`
as is suggested [here](https://github.com/ansible/ansible/issues/34056#issuecomment-352862252).

Also see https://github.com/ansible/ansible/pull/31500

**Comment by taspinar** [comment]
I'll close this issue for now.
