### ISSUE TITLE
Required only tweet text

### ISSUE THREAD

**Issue by atuljha23** [taspinar/twitterscraper#107]
Hi i want only tweet text to be extracted.  No Username, timestamp, retweet or anything. how to achieve that?

**Comment by rreid12** [comment]
From within python, you can use just the text from tweets like this:

```
list_of_tweets = query_tweets("Trump OR Clinton", 10)
for tweet in list_of_tweets:
    print(tweet.text)
```
I don't think it's possible from the CLI without the use of python.
