### ISSUE TITLE
UnboundLocalError: local variable 'pool' referenced before assignment

### ISSUE THREAD

**Issue by 3ruce** [taspinar/twitterscraper#114]
I've been running this script successfully for a while but on upgrading to 0.7.0 I get this error on my local machine and on a server. Both are running ubuntu 16.04

Here's the script command

`twitterscraper "bread" -bd "2018-05-24" -ed "2018-05-24" --output=tweets-01.json`

And here's the error

```
Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 9, in <module>
    load_entry_point('twitterscraper==0.7.0', 'console_scripts', 'twitterscraper')()
  File "build/bdist.linux-x86_64/egg/twitterscraper/main.py", line 93, in main
  File "build/bdist.linux-x86_64/egg/twitterscraper/query.py", line 182, in query_tweets
UnboundLocalError: local variable 'pool' referenced before assignment

```

**Comment by 3ruce** [comment]
upgrading twitterscraper via `sudo pip install --upgrade twitterscraper` fixed this...

**Comment by theGreatGiorgio** [comment]
The problem is actually still relevant.

**Comment by fonzmeister** [comment]
I got this problem as well. Solved it by upgrading beatifulsoup4 -> 4.6.3

**Comment by gastondg** [comment]
Get same error on AWS Lambda when testing.
Any recommendations?

**Comment by jamessugrue** [comment]
Having the same issue here on AWS Lambda

**Comment by jamessugrue** [comment]
I think it's down to a similar issue to that referenced [here](https://github.com/mozilla-services/remote-settings-lambdas/issues/60): 
I'll try and create a Pull Request to deal with it

**Comment by kewp** [comment]
Random suggestion: have you tried wrapping the whole script in `if __name__ == "__main__"` ? For some reason I was getting this error on windows and that fixed it (from the suggestion here https://github.com/stan-dev/pystan/issues/364 no idea why it worked)
