### ISSUE TITLE
Are all tweets collected?

### ISSUE THREAD

**Issue by NileshJorwar** [taspinar/twitterscraper#130]
When I ran the query I get 85% of total tweets? However, after analysis, I could see that I could get only those tweets which are "replies" by twitter handle to the general public or "tweet" by twitter handle.
How to collect the incoming messages to the twitter handle and how to gather all the retweets to the tweet originated by the twitter handle?

**Comment by NileshJorwar** [comment]
When I queried for the tweets between June 1 2018 to till date, I got the tweets similar to the advanced search option of the Twitter when queried for the same period. But when I went on the @amazon on twitter , it included those tweets "amazon.com retweeted" mentioned. But when I clicked on the retweets i could not find the @amazon but its other handles like @amazonnews, amazonfiretv. And these tweets where it says that "amazon.com retweeted" are not included in tweets that we gather using twitterscraper.
![image](https://user-images.githubusercontent.com/36153120/42343284-3a15c4fa-805e-11e8-90f2-e58f8d2d1577.png)

As you can see in above image marked with blue color, these tweets are not included in our search criteria .

**Comment by lapp0** [comment]
Did you try what I suggested in the other comments?

Here:
>This library gets tweets from profiles rather than search:
>https://github.com/kennethreitz/twitter-scraper

And Here:
>You should try this library which gets from profiles rather than search
>
>https://github.com/kennethreitz/twitter-scraper
>
>Please report back whether it works for you

As we discussed with you in those threads, twitter search doesn't  show retweets, so you should try the library which gets the tweets from specific profiles which I am pointing out to you again:

https://github.com/kennethreitz/twitter-scraper

**Comment by taspinar** [comment]
@NileshJorwar twitterscraper does not scrape retweets, as also discussed in https://github.com/taspinar/twitterscraper/issues/92

**Comment by taspinar** [comment]
This issue should be fixed in version 0.9.0
