### ISSUE TITLE
module' object has no attribute 'getLogger'

### ISSUE THREAD

**Issue by jamesozden** [taspinar/twitterscraper#132]
So it seems like I have multiple files named logger.py which is stopping me from using twitterscraper, evident from:

module' object has no attribute 'getLogger'

 However, I'm not sure what the best way to resolve this is, so any input would be much appreciated!

**Comment by lapp0** [comment]
Hey, it looks like I screwed this one up. Downgrade to `0.7.0` or upgrade to `python3`.

@taspinar looks like naming it `logger.py` can cause issues too. I need to test more extensively.

**Comment by lapp0** [comment]
hello can you please try the branch in this pull request? Should fix it https://github.com/taspinar/twitterscraper/pull/135

**Comment by taspinar** [comment]
PR #135 has been merge and version 0.8.0 has been uploaded to PyPi. This issue should be fixed.
