### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getLogger'

### ISSUE THREAD

**Issue by s5joschi** [taspinar/twitterscraper#134]
I installed twitterscraper with pip 10.0 and After trying the example code  `twitterscraper Trump --limit 100 --output=tweets.json`, I get the following error message:

```

/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 7, in <module>
    from twitterscraper.main import main
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/__init__.py", line 13, in <module>
    from twitterscraper.query import query_tweets
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/query.py", line 10, in <module>
    from twitterscraper.logging import logger
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/logging.py", line 4, in <module>
    logger = logging.getLogger('twitterscraper')
AttributeError: 'module' object has no attribute 'getLogger'

```

**Comment by lapp0** [comment]
hello can you please try the branch in this pull request? Should fix it https://github.com/taspinar/twitterscraper/pull/135

**Comment by s5joschi** [comment]
Just reinstalled it on another ubuntu and I get the same problem. I tried to install the branch with  `pip install git+https://github.com/taspinar/twitterscraper.git@issue/135/`. But no success. could you help me out with the full pip command?

**Comment by lapp0** [comment]
It's been merged into master, just try to install it from master.

For future reference, https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by s5joschi** [comment]
Seems to work now. However pip installation is broke. I installed it by cloning and than via python. Thanks for the reference. That's the one I used. I just was not able to find out the branch name and create a correct link.
