### ISSUE TITLE
Exiting with error

### ISSUE THREAD

**Issue by aasimali141290** [taspinar/twitterscraper#144]
<img width="565" alt="screen shot 2018-08-10 at 3 28 26 pm" src="https://user-images.githubusercontent.com/23409265/43977403-16fd5120-9cb2-11e8-874a-53de84615a98.png">

Os: Ubuntu 16.04
Python: Python 3.5
replicate with the command
$ nohup twitterscraper VinnyLingham -bd 2017-06-01 -ed 2017-12-01 -o VinnyLingham.json &

**Comment by nbreide** [comment]
I am also having this issue. 

Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 9, in <module>
    load_entry_point('twitterscraper==0.9.0', 'console_scripts', 'twitterscraper')()
  File "/Library/Python/2.7/site-packages/twitterscraper/main.py", line 105, in main
    with open(args.output, "w", encoding="utf-8") as output:
TypeError: 'encoding' is an invalid keyword argument for this function

OS: MacOS High Sierra 10.13.4
Python: Python 2.7
command: 
$ twitterscraper AskCiti -bd 2013-08-13 -ed 2018-08-13 -o askcititwitter.json

**Comment by 3ruce** [comment]
interesting, me too...

**Comment by 3ruce** [comment]
Building from this commit worked for me... https://github.com/taspinar/twitterscraper/commit/6231834473d281d4cce0cf4ba806a1207ca8a19e

**Comment by NathanLazarus** [comment]
I had this error running Python 2.7.15 on two Windows 10 machines. Switching to Python 3.7.0 fixed it on both.

**Comment by taspinar** [comment]
Python 2.x's <code>open()</code> method does not contain the <code>encoding</code> parameter. See [here](https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2).

Although twitterscraper is not designed to work with Python 2.x, I will rewrite this part to use <code>codecs.open()</code> instead of <code>open</code>

**Comment by taspinar** [comment]
This issue should be fixed in version 0.9.3 which uses codecs.open() to open a file instead of open().
