### ISSUE TITLE
Not getting all tweets from a specific user.

### ISSUE THREAD

**Issue by rum-n** [taspinar/twitterscraper#158]
Hey, first of all, thanks for creating this!
Second, I'm trying to get all tweets from a single user, but can't seem to do it. 

Here's my query:

twitterscraper tiankovbot -u -o tweets_tiankov.json
INFO: Got 819 tweets from username tiankovbot

The user currently has >3500 tweets.

Am I missing something?

**Comment by taspinar** [comment]
Hi @rum-n 
The number of tweets indicated on a profile (in this case 3522) is usually larger than the actual number of tweets. It does not get updated when (large number of) tweets are deleted. 
The actual number of tweets by tiankovbot is 820...
You can check this by scrolling down on his profile page, and when you have reached the bottom hit CTRL + J to open developers console (in google chrome) and search (CTRL + F) in the "Elements" tab for " js-stream-item".

**Comment by rum-n** [comment]
Got it! Thanks a lot for the quick response!
