### ISSUE TITLE
How to save output as JSON in python

### ISSUE THREAD

**Issue by ehsong** [taspinar/twitterscraper#160]
```
output = query_tweets( .. )
 jsonfile = open("tweets.json","w")
    for tweet in output:
        json.dump(tweet,jsonfile)
    jsonfile.close()
```
`TypeError: Object of type Tweet is not JSON serializable`

How can I properly store the tweets as json file?
I also tried appending each tweet in output in a list, but this did not work either.

**Comment by DaewonSeo** [comment]
```
import json
from datetime import datetime
from twitterscraper import query_tweets

jsonfile = open("tweets.json","w")
list_of_tweets = query_tweets('Trump', 10)
list_of_json = [] # create empty list to save multiple tweets which is type of json(dictionary)

```
Below tweets variable, not string and number but python Class Object.
In tweets variable, there are many class variables like user, fullname, id, url, timestamp, test, replies, retweets, likes, html. 
you could check this below url. To access tweets data, you should use tweets.user, tweets.fullname, tweets.id ~

[tweet.py](https://github.com/taspinar/twitterscraper/blob/master/twitterscraper/tweet.py)


```
for tweets in list_of_tweets: # for looping
    tweets.timestamp = datetime.strftime(tweets.timestamp, '%Y-%m-%d %H:%M:%S')
    list_of_json.append(vars(tweets))
```

Second, tweets.timestamp is datetime object, not string. If you wanna save this data to json, change datetime to string type. vars() method is to get class __dir___ object(please search about this)

below is the result of vars(tweets)

`{"user": "watsupeurope", "fullname": "WatsupEurope", "id": "866081100006928384", "url": "/watsupeurope/status/866081100006928384", "timestamp": "2017-05-20 23:59:59", "text": "#Europe: USA: Democrat congress members call for investigation into Trump\u2019s alleged collusion with Russia https://goo.gl/Qd8Rmt\u00a0", "replies": "0", "retweets": "0", "likes": "0", "html": "<p class=\"TweetTextSize js-tweet-text tweet-text\" data-aria-label-part=\"0\" lang=\"en\"><a class=\"twitter-hashtag pretty-link js-nav\" data-query-source=\"hashtag_click\" dir=\"ltr\" href=\"/hashtag/Europe?src=hash\"><s>#</s><b>Europe</b></a>: USA: Democrat congress members call for investigation into <strong>Trump</strong>\u2019s alleged collusion with Russia <a class=\"twitter-timeline-link\" data-expanded-url=\"https://goo.gl/Qd8Rmt\" dir=\"ltr\" href=\"https://t.co/R3NQwvutUW\" rel=\"nofollow noopener\" target=\"_blank\" title=\"https://goo.gl/Qd8Rmt\"><span class=\"tco-ellipsis\"></span><span class=\"invisible\">https://</span><span class=\"js-display-url\">goo.gl/Qd8Rmt</span><span class=\"invisible\"></span><span class=\"tco-ellipsis\"><span class=\"invisible\">\u00a0</span></span></a></p>"}`


`json.dump(list_of_json, jsonfile)`

Lastly, list_of_tweets have 10 tweets about "Trump". append each json to list to save total json file(tweets.json)

If you wanna know more information look at this [repository code](https://github.com/taspinar/twitterscraper/tree/master/twitterscraper) and read python documentation about [Class](https://docs.python.org/3/tutorial/classes.html)

**Comment by ehsong** [comment]
Hi! Thanks for the comment, I appreciate it.

**Comment by gnfrazier** [comment]
The portion that was not obvious to me was this line. Thanks!

`tweets.timestamp = datetime.strftime(tweets.timestamp, '%Y-%m-%d %H:%M:%S')`

**Comment by taspinar** [comment]
Hi all,
For more info on how to save tweets, i suggest you have a look at the code in main.py.
Basically they can be saved with json by passing the JSONEncoder class as an argument.
‘json.dumps(tweets, cls=JSONEncoder)’

JSOnEncoder is an extension to the standard JSON serializer which contains the datatypes not supported natively by JSON (like datetime) and convert them into datatypes which can be serialized. (For more info see http://www.diveintopython3.net/serializing.html#json-unknown-types).
