### ISSUE TITLE
CSV separator

### ISSUE THREAD

**Issue by Allacius** [taspinar/twitterscraper#163]
Hello, 
I just wanted to know whether there were a way to change the default separator of the csv file output. 
The "," is quite a frequent character in tweets, and the results of this is that often the csv file get all messed up. 
Thanks for the great job!

**Comment by taspinar** [comment]
In line 107, you could add the delimiterargument. Like this:
`f = csv.writer(output, delimiter=";")`

A better way could be to first load the tweets into a pandas dataframe and then save it as csv.

**Comment by taspinar** [comment]
In the new version of twitterscraper, the CSV separator is set to ';' by default.
