### ISSUE TITLE
Proxy network support

### ISSUE THREAD

**Issue by jchook** [taspinar/twitterscraper#164]
Hello, excellent software. I have used twitterscraper with great success.

However, I don't see any easy way to enable internet proxies.

Am I missing something built-into python or perhaps an undocumented option? Perhaps I could use an SSH tunnel or `nc` or similar?

**Comment by jchook** [comment]
Okay, found it!

Since twitterscraper uses [`requests`](http://docs.python-requests.org/), we can simply use the [`HTTPS_PROXY` environment variable](http://docs.python-requests.org/en/master/user/advanced/#proxies).

I verified this works by trying a bogus proxy address to make sure generated a proxy error (it did).

For example:

```
HTTPS_PROXY="http://222.124.22.133:80/" twitterscraper -o tweets-dt.json 'from:realDonaldTrump'
```

**Comment by fzxiao233** [comment]
Hello, could provide proxy network support within python?

**Comment by jchook** [comment]
@fzxiao233 I think you can set the environment variable from within python, e.g.

```python
os.environ["HTTPS_PROXY"] = "http://222.124.22.133:80/"
```

**Comment by fzxiao233** [comment]
> 
> 
> @fzxiao233 I think you can set the environment variable from within python, e.g.
> 
> ```python
> os.environ["HTTPS_PROXY"] = "http://222.124.22.133:80/"
> ```

Thank you, it's a nice method.
