### ISSUE TITLE
Parralel scraping doesn't seem to work

### ISSUE THREAD

**Issue by sils** [taspinar/twitterscraper#17]
I did a few logging modifications and if you checkout https://github.com/sils/twitterscraper/tree/sils/parallel and scrape for `test` or something like that you'll get like 60ish tweets sometimes for some parts of months which seems rather impossible (and doesn't check out if you put in the advanced query into the search UI)

@taspinar if you have any idea that'd help a lot :/

**Comment by sils** [comment]
Also it seems that even without scraping in parallel (using map instead of the pool's imap) those big queries don't really work too well.

**Comment by adtac** [comment]
Hi, I'd like to take this up. Can I get assigned?

PS: @sils pointed me over here :)

**Comment by taspinar** [comment]
Hi @adtac , it would be great if you could have a look at it :)

**Comment by adtac** [comment]
@sils could you post the json somewhere? I tried running `TwitterScraper "hillary OR trump AND election" --limit 100` and all the output tweets were properly in December 2016. Should I try with `-a`?

**Comment by sils** [comment]
problem seems to appear only withlarge amounts of tweets

**Comment by adtac** [comment]
Rough order? I'm currently running it for 100,000 tweets.

**Comment by adtac** [comment]
@sils just came back - there doesn't seem to be any tweet with a weird month - `timestamp.month` is always between `1` and `12` (inclusive). Any pointers as to how to reproduce this issue?

**Comment by sils** [comment]
@adtac checkout my branch and scrape for `test` without limit. You will see that for some queries there's a very low number of results, the queries are logged with the number of results on that branch: paste the exact query to the search box in https://twitter.com/ and you'll see that there are way more results in the web UI for that query than were scraped.

**Comment by adtac** [comment]
@sils Yay, I was able to reproduce it :+1: Some months returned 0 results (when results actually exist).

I made this small change and after several tests I never got the problem again. I haven't concluded if this is the *the* issue. Still looking into it.

```diff
diff --git a/twitterscraper/query.py b/twitterscraper/query.py
index 12a2880..bb5dca7 100644
--- a/twitterscraper/query.py
+++ b/twitterscraper/query.py
@@ -84,7 +84,7 @@ def query_tweets_once(query, limit=None, num_tweets=0):
     :return:      A list of twitterscraper.Tweet objects. You will get at least
                   ``limit`` number of items.
     """
-    query = query.replace(' ', '%20').replace("#", "%23")
+    query = query.replace(' ', '%20').replace("#", "%23").replace(":", "%3A")
     pos = None
     tweets = []
     try:
```

**Comment by adtac** [comment]
I have, however, been getting a few weird `ERROR: URLError EOF occurred in violation of protocol (_ssl.c:600) while requesting` sometimes :/

**Comment by sils** [comment]
is that disturbing the scraping or is the retry mechanism catching it?

**Comment by adtac** [comment]
The retry catches it and then things resume on well after that.

**Comment by adtac** [comment]
Probably just a issue with my network - it's a little flaky at the moment.

**Comment by sils** [comment]
sounds fine then

**Comment by adtac** [comment]
Yeah, it's working quite well now - none of the first 20 parallel workers have finished (each at > 2500 tweets atm).

**Comment by sils** [comment]
nice, make a PR?

**Comment by adtac** [comment]
Starting from your branch? I guess it doesn't really matter - you can rebase later.

**Comment by sils** [comment]
my commit is a WIP, pull in all changes that are good, I think the logging like that is better and more transparent

**Comment by adtac** [comment]
I disagree with [removing this](https://github.com/sils/twitterscraper/commit/d3a84fa1710be3a8d6774c36f5b42de8a21805ef#diff-84e7bb41f8dfc0c9956b29d20320e1bcL101) - it's hard to know what's going on in the background if there're no updates. For example `test` has over 3000 tweets (and counting) and I have no idea if it is even running (3000 tweets =~ 150+ http requests =~ 3 or 4 minutes at the very least). In fact I added in a simple

            logging.info(repr(query) + " - " + str(len(tweets)))

just to keep myself updated :D

Also I don't understand why we don't need [Line 87](https://github.com/sils/twitterscraper/commit/d3a84fa1710be3a8d6774c36f5b42de8a21805ef#diff-84e7bb41f8dfc0c9956b29d20320e1bcL87).

**Comment by adtac** [comment]
But I agree with the other two changes :+1:

**Comment by sils** [comment]
I was just trying to make it less verbose so I could see the relevant stuff

**Comment by adtac** [comment]
Ah, alright :3

I'll make a PR in a minute :+1:
