### ISSUE TITLE
error in getting user's tweet

### ISSUE THREAD

**Issue by yyzhuang1991** [taspinar/twitterscraper#171]
when I ran "twitterscraper realDonaldTrump -u -o tweets_username.json", the following error was raised: 
     
> `File :twitterscraper/venv/lib/python3.6/site-packages/twitterscraper-0.9.3-py3.6.egg/twitterscraper/query.py", line 222, in query_tweets_from_user
    new_tweets, pos = query_single_page(query, lang='', pos=pos, from_user=True)`
> `NameError: name 'query' is not defined
INFO: Got 0 tweets from username realDonaldTrump.`

**Comment by 0xMilly** [comment]
You only have to change `query_single_page(query, lang='', pos=pos, from_user=True)` to `query_single_page(user, lang='', pos=pos, from_user=True)`. This is being fixed in 0xMilly/twitterscraper@c4a0f715d8f24502c20f4d7ccbd8cf625163d792 . (:

**Comment by taspinar** [comment]
Fixed with #191
