### ISSUE TITLE
Exception has occurred: ImportError

### ISSUE THREAD

**Issue by sxshateri** [taspinar/twitterscraper#188]
hey guys im trying to find out how this script works on visual studio code but it just doesnt work and im getting "Exception has occurred: ImportError" error.
here is the complete error:

`Exception has occurred: ImportError
cannot import name 'query_tweets' from 'twitterscraper' (c:\Users\Dell\Documents\python 2\twitterscraper.py)
  File "C:\Users\Dell\Documents\python 2\twitterscraper.py", line 1, in <module>
    from twitterscraper import query_tweets
  File "C:\Users\Dell\Documents\python 2\twitterscraper.py", line 1, in <module>
    from twitterscraper import query_tweets`

**Comment by taspinar** [comment]
Hi @sxshateri 
Twitterscraper does not work properly for Python2. Can you install Python3? Time is running out on Python2 anyway.

The right way to import a function from the `query` module is as follows:
`from twitterscraper.query import query_tweets`

**Comment by avanibhatnagar** [comment]
I'm using Python 3.8 and I still get the same import error: 
    ```
from twitterscraper import query_tweets
ImportError: cannot import name 'query_tweets' from partially initialized module 'twitterscraper' (most likely due to a circular import) (D:\Users\avani.bhatnagar\Dropbox (Icimo, LLC)\Data Analyst\Analyst Folders\Avani\voir api\twitterscraper.py)
```

**Comment by avanibhatnagar** [comment]
I'm using Python 3.8 and I still get the same import error:
```
from twitterscraper import query_tweets
ImportError: cannot import name 'query_tweets' from partially initialized module 'twitterscraper' (most likely due to a circular import) (D:\Users\....\twitterscraper.py)
```

Where twitterscraper.py is the `get_twitter_user_data.py` from examples in this repo

**Comment by DeepanjalShr** [comment]
Hi, I am unable to run twitter scraper, it gives the under mentioned error. Please help!
cannot import name 'query_tweets' from 'twitterscraper' (C:\Users\user\.spyder-py3\twitterscraper.py)

**Comment by JiggsUK** [comment]
I had the same issue and I used:
`import twitterscraper
twitterscraper.query_tweet(user, limit)`

This gave me access to the modules in twtterscraper when none of the examples worked.

**Comment by Robgroe** [comment]
I am running into the same problem, did you fix it? If so, how?
