### ISSUE TITLE
Can I obtain the replies of a tweet?

### ISSUE THREAD

**Issue by VolodyaCO** [taspinar/twitterscraper#193]
If I have a tweet with an id, can I pass this id to twitterscrapper to obtain all replies of the original tweet?

**Comment by taspinar** [comment]
No, but you can obtain the replies to an person and then filter out the result.

**Comment by VolodyaCO** [comment]
@taspinar And how can I do that? The tweets that are replies to a person (with the option "filter:replies" in the advanced search) do not mention the id of the tweet they are replying to.

For example `twitterscraper "cmilanoticia filter:replies" -l 1000 -bd 2019-06-13 -ed 2019-06-15 -o tweets.json` gives only tweets that are replies to cmilanoticia, but I do not know which tweets reply to which tweet.

**Comment by taspinar** [comment]
Can you have a look at https://github.com/taspinar/twitterscraper/pull/100. 
I believe that is what you're looking for.

**Comment by VolodyaCO** [comment]
@taspinar So I'd have to modify tweet.py to implement what you are saying, right?

Because this reply_to_id idea is not implemented right now

**Comment by taspinar** [comment]
No not yet.

**Comment by VolodyaCO** [comment]
I modified tweet.py and got what I needed. Thanks @taspinar I will close this issue.
