### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by chamilton-turner** [taspinar/twitterscraper#199]
I just started working with this tool, but I continue getting this Logging error:

`TypeError: not all arguments converted during string formatting`

I am running with the standard CLI synatx provided in the readme:

`twitterscraper angry -l 1000 -o angry.json`

I get this error whether I pass the query with quotes or not. Am I missing something here?

Also, is it possible to scrape specific hashtags? Thank you!

**Comment by Kallirroi** [comment]
Same here.

**Comment by mchbmn** [comment]
likewise, when used in CLI, calling specific functions `query_tweet` or others in Jupyter works, though requires manual conversion to csv.

**Comment by luchong12** [comment]
I get this when using it from the API (query_tweets) too

**Comment by mchbmn** [comment]
As a temporary solve I have reverted to 0.9.3, which works:

`pip install twitterscraper==0.9.3`

Want that new retweet functionality though

**Comment by liaoming999** [comment]
same here

**Comment by Captain-F** [comment]
Same here.

**Comment by michael-wise** [comment]
Haven't used this lib in a while. Just hopped on it to try something, and had this error with fresh install from pip3 from python query_tweets method. 
```python
tweets = twitterscraper.query.query_tweets(query="@jwucharlotte", begindate = datetime.date(2019,7,23), enddate = datetime.date(2019,7,24))
```

I verified `pip install twitterscraper==1.1.0` is the latest version available in pip that avoids this issue.

**Comment by taspinar** [comment]
Like @yvelkram noticed this was due to a typo and it should be fixed in the latest version of twitterscraper==1.3.0
