### ISSUE TITLE
Date issue occurring again - Cannot pass in a date earlier than one week ago

### ISSUE THREAD

**Issue by norajones** [taspinar/twitterscraper#2]

**Comment by taspinar** [comment]
Hi Nora Jones,
The version on GitHub should be working fine. There was a problem with the version numbering on PyPI so the latest changes were not present there and could not be seen when installing with `pip install twitterscraper`. However, the version number has been updated and it should be working fine now when installed from PyPi. 

Can you also check it?

**Comment by norajones** [comment]
Hi Taspinar,

I actually copied the code directly from github. It worked great momentarily, but now I'm having the same issue as before with the dates where it will not go back further than a week. It's as if some sort of notification occurred that enabled Twitter to know I was trying to go back further than a week.

Thanks,
Nora

On Jul 24, 2016, at 7:23 AM, taspinar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Nora Jones,
The version on GitHub should be working fine. There was a problem with the version numbering on PyPI so the latest changes were not present there and could not be seen when installing with pip install twitterscraper. However, the version number has been updated and it should be working fine now when installed from PyPi.

Can you also check it?

-

**Comment by norajones** [comment]
No 503 error is returned this time either, it simply runs for a millisecond and then, stops. Like I was saying, the changes worked momentarily, and then all of a sudden stopped - it is bizarre.

**Comment by taspinar** [comment]
Hi norajones,
Can you try to use a random (fake) User-Agent to see if this solves your problem? 

(first install fake_useragent with `pip install fake_useragent`)

on the top of the page:
`from fake_useragent import UserAgent
ua = UserAgent()`

and on line 85:
`headers = ua.random`

**Comment by norajones** [comment]
Hi Taspinar, 

Looks like this is causing other issues, 

```
generic exception: Traceback (most recent call last):
  File "twitter-scraper.py", line 92, in scrape_tweets
    response = requests.get(url, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Python/2.7/site-packages/requests/models.py", line 296, in prepare
    self.prepare_headers(headers)
  File "/Library/Python/2.7/site-packages/requests/models.py", line 407, in prepare_headers
    self.headers = CaseInsensitiveDict((to_native_string(name), value) for name, value in headers.items())
```

`AttributeError: 'unicode' object has no attribute 'items'
`
I've been able to reproduce both issues on separate machines as well.

**Comment by taspinar** [comment]
Yes, of course the parameters passed on to requests should be hashable. :)
try : `headers = {'User-Agent': ua.random}`

**Comment by norajones** [comment]
thanks for your help! One more error I'm getting after this runs for a bit...

```
  File "count-old-words-current.py", line 98, in scrape_tweets
    response_json = response.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Is this a result of Twitter potentially blocking?

**Comment by taspinar** [comment]
I have seen something similar last night. Most probably ua.random is returning mobile User-Agent strings, resulting in Twitter returning a mobile web-page (which has a different structure). You can see this behaviour by printing the URL: `print response.url`.
Unfortunately fake-useragent does not provide the option to select non-mobile user agent strings only.
Try the following : 
`headers_list = [ua.ie, ua.msi, ua['Internet Explorer'], ua.opera, ua.chrome, ua.google, ua['google chrome'], ua.firefox, ua.ff]`
`import random`
`headers = {'User-Agent': random.choice(headers_list) }`

**Comment by norajones** [comment]
Hm, I'm thinking, to insert a statement that allows for the program to continue if it does hit a mobile web-page.

**Comment by norajones** [comment]
Any other ideas? @taspinar

**Comment by taspinar** [comment]
There is something strange with the Requests package resulting in the mobile URL (even though the User-Agent is not mobile). As far as I have seen, this is not the case for urllib2.
Can you check if the newest version works without any problems?

**Comment by norajones** [comment]
Just checked the new version, not getting the same errors, but now getting 404s back at a certain point in scraping.

From: taspinar
Reply-To: taspinar/twitterscraper
Date: Thursday, July 28, 2016 at 7:02 PM
To: taspinar/twitterscraper
Cc: Nora Jones, Author
Subject: Re: [taspinar/twitterscraper] Date issue occurring again - Cannot pass in a date earlier than one week ago (#2)


There is something strange with the Requests package resulting in the mobile URL (even though the User-Agent is not mobile). As far as I have seen, this is not the case for urllib2.
Can you check if the newest version works without any problems?

**Comment by taspinar** [comment]
Hi Norajones,
removed internet explorer from the list of headers containing User-Agent information. The response to internet explorer (like the mobile user-agent strings) was so different that the regular dom-elements can not be used to retrieve the tweets.
