### ISSUE TITLE
Retweet_id, retweeter_userid, retweeter_username are empty 

### ISSUE THREAD

**Issue by RishengP** [taspinar/twitterscraper#201]
No matter how I changed my code, it never returns Retweet_id, retweeter_userid, retweeter_username. Can somebody help me out?

**Comment by HJoentgen** [comment]
Hey, I'm also interested in scraping retweets. With the normal search function of Twitter no retweets are shown. Does this scraper crawl the retweets but without your mentioned information?

**Comment by taspinar** [comment]
Hi @RishengP and @HJoentgen 
As mentioned in 2.4.0 you can only obtain retweets if you scrape all of the tweets from an user profile. 
Since a normal search does not show any retweets, those field will be empty.

In any case,  I'll adapt the README file to make this more explicit.
