### ISSUE TITLE
--profiles fails using Command Line

### ISSUE THREAD

**Issue by johannstark** [taspinar/twitterscraper#218]
Trying to make a query like this one:
`twitterscraper gundam -l 10 -bd 2019-8-22 -ed 2019-8-23 -o gundamFile.json --profiles`

Creates the JSON file but fails with the profiles:

> Traceback (most recent call last):
>   File "/anaconda3/bin/twitterscraper", line 10, in <module>
>     sys.exit(main())
>   File "/anaconda3/lib/python3.7/site-packages/twitterscraper/main.py", line 126, in main
>     list_users = list(set([tweet.user for tweet in tweets]))
>   File "/anaconda3/lib/python3.7/site-packages/twitterscraper/main.py", line 126, in <listcomp>
>     list_users = list(set([tweet.user for tweet in tweets]))
> AttributeError: 'Tweet' object has no attribute 'user'

**Comment by Lidl-to-go** [comment]
I have the same problem, need help

**Comment by marquisvictor** [comment]
@johannstark @Lidl-to-go  Check this Improvement fork i made to a twitter scraping package originally built by Jefferson Henrique. It worked and works for me. 

https://github.com/marquisvictor/Modified-GetOldTweets3

**Comment by johannstark** [comment]
@marquisvictor @Lidl-to-go the issue is a tiny word at line 126 of a single file
insted of "twee.user" is "tweet.username"

**Comment by Lidl-to-go** [comment]
@johannstark  Tank you so much! it works!
@marquisvictor  Tank you also !
