### ISSUE TITLE
Option to disable proxying requests

### ISSUE THREAD

**Issue by gbspend** [taspinar/twitterscraper#222]
My university network blocks proxy websites, including the one hardcoded into this application, meaning that when I try to run it I get HTTP errors when `get_proxies()` is run upon loading query.py (i.e. I can't even run "`twitterscraper -h`").
I downloaded the source and commented out the proxy parts of query.py, including removing the `proxies` parameter from `response = requests.get(url, headers=HEADER, proxies={"http": proxy})`. I then was able to use the application on my university network with no issues.
Please include an option to disable the use of proxies for those users like me who are unable to connect via proxies due to circumstances outside of our control.
Thank you!

**Comment by haseebelahi** [comment]
Hey @gbspend! I opened #234 for this, will get fixed once the PR gets merged!
