### ISSUE TITLE
Filter retweets?

### ISSUE THREAD

**Issue by Sodawrap** [taspinar/twitterscraper#254]
Hi,

Dumb question I know, I scraped about 30 thousand tweets but I don't want retweets, just originals. is there a way to do this? Or at least see check if something is a retweet?

Thanks!

**Comment by bburakkoksal** [comment]
Hi,

Have you found a way to do this? I need to exclude the retweets too.

**Comment by lapp0** [comment]
`myquerystring -filter:nativeretweets`
