### ISSUE TITLE
How to get tweets in a city?

### ISSUE THREAD

**Issue by Ubaid93** [taspinar/twitterscraper#262]
Hi I want to get the tweets in Melbourne . 

> 
> begin_date = dt.date(2014,1,1)
> end_date = dt.date(2014,7,5)
> limit = 100000000
> tweets = query_tweets('oz comic con', begindate = begin_date, enddate = end_date, limit = limit)
> df1 = pd.DataFrame(t.__dict__ for t in tweets)
> export_csv = df1.to_csv (r'C:\Users\ubaid\oz_comic_con_2014.csv', index = None, header=True)

What should I do to get the tweets only in Melbourne?. Please look at the code above (I am using python)

I am not sure how to use near function

**Comment by Ubaid93** [comment]
Not sure how to use near function

**Comment by lethalbeans** [comment]
Any luck on this?

**Comment by Ubaid93** [comment]
nope

**Comment by lethalbeans** [comment]
Ok cheers, I've been using GetOldTweets3 - managed to scrape 50k tweets via geolocation.

**Comment by Ubaid93** [comment]
@lethalbeans can you please help me out on how to get them?

**Comment by lethalbeans** [comment]
https://github.com/Mottl/GetOldTweets3 

It has good documentation, scroll near the bottom. It tells you how to scrape in Python.

**Comment by lethalbeans** [comment]
> @lethalbeans can you please help me out on how to get them?

https://github.com/Mottl/GetOldTweets3

It has good documentation, scroll near the bottom. It tells you how to scrape in Python.

**Comment by Ubaid93** [comment]
I have tried that but it only gives a very limited amount of tweets. Please share a chunk of code if possible

**Comment by smuotoe** [comment]
> Hi I want to get the tweets in Melbourne .
> 
> > begin_date = dt.date(2014,1,1)
> > end_date = dt.date(2014,7,5)
> > limit = 100000000
> > tweets = query_tweets('oz comic con', begindate = begin_date, enddate = end_date, limit = limit)
> > df1 = pd.DataFrame(t.**dict** for t in tweets)
> > export_csv = df1.to_csv (r'C:\Users\ubaid\oz_comic_con_2014.csv', index = None, header=True)
> 
> What should I do to get the tweets only in Melbourne?. Please look at the code above (I am using python)
> 
> I am not sure how to use near function

You could include the near operator in your query. e.g. tweets = query_tweets("'oz comic con' near:Melbourne" begindate = begin_date, enddate = end_date, limit = limit)

**Comment by lapp0** [comment]
thanks @smuotoe
