### ISSUE TITLE
Missing the Output JSON file ...

### ISSUE THREAD

**Issue by GeekByFreak** [taspinar/twitterscraper#28]
This question might sound silly, but I am able to use TwitterScraper successfully (with the command twitterscraper “<my keywords>” --output=tweets.json”. but I am unable to retrieve my json file (Logging shows that data is being collected:  Example : 
INFO: Got 137 tweets (20 new).
INFO: Got 157 tweets (20 new).
INFO: Got 177 tweets (19 new).
INFO: Got 196 tweets (19 new).
¸INFO: Got 215 tweets (17 new).
INFO: Got 232 tweets (20 new).
INFO: Got 252 tweets (19 new). 
)
Specifying the exact path /Users/blahblah/tweets.JSON did not make a difference. 
What am I missing? Thanks for your help in advance,

**Comment by taspinar** [comment]
Hi @GeekByFreak , Could you try to output with the command "twitterscraper -o filename query" 
with the latest version (install either from github or from pypi).

**Comment by GeekByFreak** [comment]
Thanks @taspinar. Just did that. 
bash-3.2$ twitterscraper -o tweets.JSON "weather" 

INFO: Running iteration no 1, query is 'weather'

INFO: Querying weather

INFO: Got 0 tweets (20 new).

INFO: Got 20 tweets (20 new).

INFO: Got 40 tweets (18 new).

INFO: Got 58 tweets (19 new).

INFO: Got 77 tweets (20 new).

^Z

[4]+  Stopped                 twitterscraper -o tweets.JSON "weather"

bash-3.2$ ls 

But still no .JSON file... :-<

**Comment by sils** [comment]
uhm from that log you pressed Ctrl+Z which on a normal unix system suspends the process so the process never ends nor continues and you will not get any JSON file. Press Ctrl+C instead to save everything it scraped until then!

**Comment by sils** [comment]
@adtac is this connected to your issue?

**Comment by adtac** [comment]
@sils Nope, @GeekByFreak is suspending the process. So the program never got to the file write phase. (BTW, the Ctrl-C issue happens only when multiprocessing is involved - so it doesn't happen for commands with limits.)

@GeekByFreak try running `fg`. This will resume the suspended process. And in the future, you should probably use Ctrl-C :)

**Comment by GeekByFreak** [comment]
I feel silly now :-( :-p. Thank you all for your quick help!
