### ISSUE TITLE
Impossible to have other data than tweet

### ISSUE THREAD

**Issue by Totogaga2** [taspinar/twitterscraper#283]
Here is my code and when I run it I can only obtain the tweets but no information like: #of likes, RT, username,...
Thanks in advance
```
from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
from twitterscraper import query_tweets_from_user
import json

start_date=dt.date(2019,4,10)
end_date=dt.date(2019,4,15)
limit=100
lang='english'

with open('output.csv', 'w+') as file:
    for tweet in query_tweets('Tiger King',begindate=start_date,enddate=end_date,limit=limit,lang=lang):
        file.write(str(tweet.text.encode('utf-8'))+'\n')
file.close()
```
![twitterscraper](https://user-images.githubusercontent.com/63740217/79365579-cc321b80-7f18-11ea-917e-0d5e452aa25d.PNG)

**Comment by lapp0** [comment]
you are using `tweet.text`. If you observe the `Tweet` class in `tweet.py`, it has the attribute `Tweet.likes`, `Tweet.retweets`, etc. Please check out that file to see what attributes are available for your consumption.
