### ISSUE TITLE
Previously installed Twitterscraper now not working

### ISSUE THREAD

**Issue by HandyTralee** [taspinar/twitterscraper#294]
I am using Jupyter notebook and until last night I was successfully running Twittersscraper having installed it using _!{sys.executable} -m pip install twitterscraper_  in the Jupyter notebook.

Today I continue to get an error 
_Could not find a version that satisfies the requirement coala-utils~=0.5.0 (from twitterscraper) (from versions: none)_ and cannot  load it.

I have also used _pip install twitterscraper_ at the Jupyter Terminal but keep getting this error 
_Could not find a version that satisfies the requirement coala-utils~=0.5.0 (from twitterscraper) (from versions: none)_

Any ideas ?

**Comment by lapp0** [comment]
share the output of `pip3 freeze`
