### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sils** [taspinar/twitterscraper#3]
Would be nice to be able to use this in python 3.

(pythonclock.org :))

**Comment by sils** [comment]
I do have it on my fork though it doesn't seem to work yet (the original didn't work with python 2 for me as well)

https://github.com/sils/twitterscraper

But this would remove support for python 2

**Comment by taspinar** [comment]
Hi sils, These are some nice changes!  If you file a pull request I can merge it. I also found a way to make it work for both python 2.7 and 3 :)

By the way, why doesnt it work for 2 for you?

**Comment by sils** [comment]
I made a PR, apparently there are conflicts, I don't have time right now to resolve this.

I just don't like working with python 2, I do everything with 3 nowadays, working with 2 is always cumbersome.

**Comment by sils** [comment]
oh yeah I have no idea what went wrong with python 2 anymore but I didn't get this to work. I may try again in near future since alternative approaches seem to fail.

**Comment by ArchibaldArt** [comment]
Sils, does your twitterscraper fork work on python 3 or still not? ("I do have it on my fork though it doesn't seem to work yet")

**Comment by sils** [comment]
```python
lasse@lsx1 ~/prog/twitterscraper (git)-[master] % python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twitterscraper import TwitterScraper
>>> topic = 'Trump'
>>> topics = ['Trump', 'Clinton'] #if there are more than one keywords, use an array. 
>>> scraper1 = TwitterScraper.Scraper(topics)
>>> a = scraper1.scrape()
collecting inf number of Tweets on the topics: Trump%20Clinton
>>> print(a)
None
```

doesn't seem to work :/

**Comment by sils** [comment]
But then again I think it did the same for me on python 2

**Comment by taspinar** [comment]
Hi sils,
I see that youre assigning the class Scraper to the variable scraper1, which should work. But then youre assigning the execution of the scrape() method to another variable 'a'... and this will not work. 
Try 'scraper1.scrape()' instead of 'a = scraper1.scrape()'.

If you want to save the results to a file you can give a filename as a parameter as indicated in one of the examples. ;)

**Comment by sils** [comment]
assignment or not, the readme shows that it should print the resuls and it
doesn't, right?

**Comment by sils** [comment]
The commands were taken straight from the readme, I just assigned and printed a to show that it returns a None explicitly.

**Comment by sils** [comment]
Ah ah ah, found it, working on ti

**Comment by sils** [comment]
So with https://github.com/taspinar/twitterscraper/pull/5 it seems to work until I get a 404 somewhere. But at least it starts scraping.

**Comment by sils** [comment]
I'm leaving you this PR, I'm working on a partial rewrite, copying only some parts of your code. It'll be a bit cleaner but I won't implement other usecases than mine specifically. However those will be addable way easier. Interested in getting this as well?

Especially having a tweet class could simplify this by far I think:

```python
class Tweet(namedtuple("Tweet", "user id timestamp fullname text")):
    @classmethod
    def from_soup(cls, tweet):
        return cls(
            user=tweet.find('span', 'username').text.encode(),
            id=tweet['data-item-id'],
            timestamp=tweet.find('a', 'tweet-timestamp')['title'],
            fullname=tweet.find('strong', 'fullname').text.encode(),
            text=tweet.find('p', 'tweet-text').text.encode()
            if tweet.find('p', 'tweet-text') else ""
        )

    @classmethod
    def from_html(cls, html):
        soup = BeautifulSoup(html, "lxml")
        tweets = soup.find_all('li', 'js-stream-item')
        if tweets:
            for tweet in tweets:
                yield cls.from_soup(tweet)
```

**Comment by sils** [comment]
Here it comes: https://github.com/sils/twitterscraper/blob/sils/auth/scrape_from_author.py

It actually works, has no shared state anywhere and - I think - is way easier to understand. Currently all the code is just dumped in that file, I may write an argparser and a CLI for the API later. I think this is considerably better maintainable and extendable.

**Comment by taspinar** [comment]
Hi Lasse,
This looks much better indeed! I actually have been thinking of getting rid of classes altogether, instead use an argument parser method which returns a dict. This would make it easier to implement multithreading/processing.

**Comment by sils** [comment]
So IMO let's drop https://github.com/taspinar/twitterscraper/pull/5#pullrequestreview-8100629 and get  https://github.com/sils/twitterscraper/blob/sils/auth/scrape_from_author.py in, making a nice API that supports all sorts of queries and an argparser with a CLI interface?

**Comment by sils** [comment]
FYI: I'll clean this up and make a CLI now. You will get a PR.

**Comment by sils** [comment]
See #7 , that does the job for me I think. May add an option for pooling multiple keywords and splitting up date ranges.

**Comment by taspinar** [comment]
Ill approve PR #7 (which is Python 3 compatible) and make it Python 2 and 3 compatible.
