### ISSUE TITLE
Is there a way to return tweets using the location parameter? 

### ISSUE THREAD

**Issue by covertbert** [taspinar/twitterscraper#30]
Am I right in thinking that this scraper only looks at `q=` to return results and therefore you cannot pass a location?

**Comment by taspinar** [comment]
Hi covertbert,
You can compose a more advanced query including the location and pass it to the twitterscraper. Have a look at https://twitter.com/search-advanced

**Comment by aliyudin21** [comment]
Hello @taspinar 

I'm new at programming.

Could you please give an example about an advanced query.  In particular scraping by location and specific time.

Thankyou
