### ISSUE TITLE
Twitterscraper is showing 0 new tweets from today 6 May 2020 1:39 am IST

### ISSUE THREAD

**Issue by abhisheksaxena1998** [taspinar/twitterscraper#301]

**Comment by zhicheng0501** [comment]
i came across the same problem

**Comment by lapp0** [comment]
Please try this and let me know how it works for you https://github.com/taspinar/twitterscraper/pull/302

**Comment by zhicheng0501** [comment]
> Please try this and let me know how it works for you #302

HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}
this works for me really good.
thank you all the same.

**Comment by abhisheksaxena1998** [comment]
HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}

This make it works in query.py. Thanks man.

**Comment by zhicheng0501** [comment]
> HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}
> 
> This make it works in query.py. Thanks man.

that is great.

**Comment by pheepa** [comment]
> HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}
> 
> This make it works in query.py. Thanks man.



> > Please try this and let me know how it works for you #302
> 
> HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}
> this works for me really good.
> thank you all the same.

where is can i set this HEADER parameters?

**Comment by lapp0** [comment]
Thanks @abhisheksaxena1998, I'll incorporate that into #302 

Closing because this is a duplicate of https://github.com/taspinar/twitterscraper/issues/296
