### ISSUE TITLE
Twitter returned : 'has_more_items'

### ISSUE THREAD

**Issue by zhicheng0501** [taspinar/twitterscraper#305]
I have using twitterscraper to pull twitter data. Every time it ends with Twitter returned:"has_more_items" even it pulled all the data already. Does anyone else see the same problem?

**Comment by zhicheng0501** [comment]
this is where the result comes from.
has_more_items = json_resp['has_more_items']
                    if not has_more_items:
                        logger.info("Twitter returned : 'has_more_items' ")
I think the code above means that it actually got all the data. Am i right?

**Comment by Kai292-tech** [comment]
I met the same output. Although I guess it should be the signal for finishing download the data, the number of output tweets is still smaller than actual number. Does anyone know why and how to refine it?

**Comment by lapp0** [comment]
@zhicheng0501 yes, that log line is misleading. I incorporated a fix  into an existing PR https://github.com/taspinar/twitterscraper/pull/302/commits/8786a5789f8686d4022f14ff44b7ffd86a5abd11
