### ISSUE TITLE
Does anyone know why "Retrying" occurs in the middle of outputs?  

### ISSUE THREAD

**Issue by Kai292-tech** [taspinar/twitterscraper#306]
I followed the aforementioned one-line solution and was still confused on why **"Retrying"** occurs in the middle of outputs. The finality as well as whole process did not tell me any error and returned to **"has more_items"**. However, I only got nearly a half of actual number. I guess I lost the **"Retrying"** pages but have no idea on why. Does anyone know the reason and solutions? Thanks a lot.

**Comment by lapp0** [comment]
`Retrying` is shown when either 
1) there is an error (failed to download, failed to parse, etc) or
2) there is no response

Counterintuitively, it appears that `has_more_items` will show if there *aren't* more items

```
                    if not has_more_items:
                        logger.info("Twitter returned : 'has_more_items' ")
                        return [], None
```
