### ISSUE TITLE
Cant extract tweets 0 tweets

### ISSUE THREAD

**Issue by VAC2018** [taspinar/twitterscraper#307]
Pls briefly describe what changes need to be done and where. 
not getting selenium installation.
pls help me

**Comment by chencc33** [comment]
I have the same issue. Got 0 tweets

**Comment by VAC2018** [comment]
mine is solved
go on earlier issues
solution is given

**Comment by lapp0** [comment]
@chencc33 please check this issue and comment https://github.com/taspinar/twitterscraper/issues/296#issuecomment-641084107
