### ISSUE TITLE
I cant connect to twitter server ，but I can connect to twitter in browser。

### ISSUE THREAD

**Issue by ZouTaooo** [taspinar/twitterscraper#325]
![NY 4N0(X )Q8~ O~AMO6IJ6](https://user-images.githubusercontent.com/28475389/87693729-e56c9180-c7bf-11ea-8167-09cd95bf269f.png)
anybody can help me ?
thx

**Comment by erb13020** [comment]
Could you kindly share your code, please?

**Comment by ZouTaooo** [comment]
![57{SK7M7J)BEYBOTV0Y7~~8](https://user-images.githubusercontent.com/28475389/87766234-6b81ea00-c84b-11ea-88c6-e72072113122.png)
when I run this program，i used shadowsocks to connect to internet，if it can cause it？
