### ISSUE TITLE
It is possible to get comments from specific tweet ? 

### ISSUE THREAD

**Issue by magicaltoast** [taspinar/twitterscraper#328]
Can i get comments from specific tweet, using direct link to tweet or tweed id ?

**Comment by taspinar** [comment]
What do you mean with comments?
All information of a tweet is saved together with tweet-id, so after scraping you can search for that specific tweet using the tweet-id.

**Comment by magicaltoast** [comment]
Nvm, i deep down in the code and i found what i was searching for
