### ISSUE TITLE
The switch --profile giving null output

### ISSUE THREAD

**Issue by j824h** [taspinar/twitterscraper#329]
After a run with the switch `--profiles`, the output `userprofiles_tweets.json` contains the value `null` for each user to be saved.

I suspect this is due to confusion of the data items.
[Twitter Help Center](https://help.twitter.com/en/managing-your-account/change-twitter-handle) | `tweet.py` | `user.py` | Usually seen
-|-|-|-
Username | `screen_name` | `user` | @j824h
Name | `username` | `full_name` | ☆jUngHyeon☆

Apparently, `main.py` must be requesting https://twitter.com/☆jUngHyeon☆ and come back with 404.

For now I have [my own fix](https://github.com/j824h/twitterscraper/tree/fix-profile-save).

Can anyone reproduce the problem?
If you do, please confirm the bug so that I can create a PR.

**Comment by taspinar** [comment]
Which command are you using for this problem to occur?

**Comment by j824h** [comment]
`twitterscraper Trump --limit 20 --profiles`

It was the command using `--profiles`, not `--profile` (sorry for confusion).

Now I can't reproduce my issue as I'm unable to obtain any result, probably related to #336, #339.
