### ISSUE TITLE
Can‘t get data earlier than 12 days ago

### ISSUE THREAD

**Issue by flash93** [taspinar/twitterscraper#33]
Hi Taspinar and Sils,

 I was collecting movie data of last year today, it seems like the date issue occurring again, I cannot get the data earlier than 12 days ago :(  and I have tried many times.  It's as if some sort of notification occurred that enabled Twitter to know I was trying to go back further than 12 days. So how can I solve this problem?

Thank you so much!

**Comment by taspinar** [comment]
Could you give some more information?

I tried the following:
`twitterscraper "musk%20since%3A2017-02-01%20until%3A2017-02-15" -o musk.json -l 1000`
and retrieved tweets from this period in february.

**Comment by flash93** [comment]
I tried this one:
`twitterscraper moana%20since%3A2016-11-09%20until%3A2016-11-10 -o moana_11_09.json`
but I only got 20 tweets.
I also tried:
`twitterscraper zootopia%20since%3A2016-03-22%20until%3A2016-03-23 -o zootopia_03_22.json`
and I got nothing :(
But I did not add quotes about the keyword, anyway I will try again.

So it is the problem about quote? 

Thank you.

**Comment by flash93** [comment]
I have tried your command line with or without the limit of 1000, but I still got nothing.
And I tried "zootopia" again, only got 80 tweets, apparently, it is not all the tweets.

Because I need to collect the tweets before or after the release time of some movies, which means I need to collect about 7 weeks' tweets, it went successfully at the beginning, but when it goes to  33th day, I can't get all tweets.

**Comment by taspinar** [comment]
That is strange, for 
`twitterscraper moana%20since%3A2016-11-09%20until%3A2016-11-10 -o moana_11_09.json`
I got 2003 tweets, 
and for 
`twitterscraper zootopia%20since%3A2016-03-22%20until%3A2016-03-23 -o zootopia_03_22.json`
i got >2400 tweets (at this point I forced it to stop)

Do you have the latest version (0.2.7) installed?

**Comment by flash93** [comment]
I do have the latest version, and I uninstalled it then installed again, but only got 100 tweets for zootopia,
`twitterscraper "zootopia%20since%3A2016-03-22%20until%3A2016-03-23" -o zootopia_03_22.json`

`INFO: Got 100 tweets for zootopia%20since%3A2016-03-22%20until%3A2016-03-23.
INFO: Got tweets ranging from 2016-03-18 to 2016-03-22
INFO: Running iteration no 2, query is 'zootopia%20since%3A2016-03-22%20until%3A2016-03-23 until:2016-03-19'
INFO: Querying zootopia%20since%3A2016-03-22%20until%3A2016-03-23 until:2016-03-19
INFO: Got 0 tweets for zootopia%20since%3A2016-03-22%20until%3A2016-03-23%20until%3A2016-03-19.`
 it is seems like twitter just forbidden me to mining more data?

**Comment by Sieboldianus** [comment]
I experienced Twitter IP blocking after about 200k tweets for a single day. In this case, either no or very few tweets would be returned. After getting a new IP, it worked just fine again. Make sure you don't query too large amounts for a single day and if you really need that much, try separating the searches into smaller increments, e.g. with
source:\"Twitter Web Client\"
source:\"Twitter for iPhone\"
...
or:
-lang:en & lang:en

or:
filter:images & exclude:images

etc.
