### ISSUE TITLE
Advance Query

### ISSUE THREAD

**Issue by aliyudin21** [taspinar/twitterscraper#34]
Hello @taspinar

I'm new at programming.

Could you please give an example about an advanced query. In particular scraping by location and specific time.

Thankyou

**Comment by taspinar** [comment]
You can use the command line interface with an advanced query as follows:

twitterscraper Trump%20near%3A"Seattle%2C%20WA"%20within%3A15mi%20since%3A2017-05-02%20until%3A2017-05-05 -o tweets.json

**Comment by aliyudin21** [comment]
Following is my code 
```
from twitterscraper import query_tweets
import time

start = time.time()


for tweet in query_tweets('Trump', 10)[:10]: 
    print tweet.user.encode("ascii", "ignore")
    print tweet.text.encode("ascii", "ignore")
    
elapsed = (time.time() - start)
print 'time:', elapsed
```
Where should I add the advanced query code ? 

`twitterscraper Trump%20near%3A"Seattle%2C%20WA"%20within%3A15mi%20since%3A2017-05-02%20until%3A2017-05-05 -o tweets.json`

Because I tried to add those code out of `for` function, then I got error message (invalid syntax).

I'm sorry, still confused with programming algorithm.

**Comment by taspinar** [comment]
Did you try running the code from the command line?

`twitterscraper Trump%20near%3A"Seattle%2C%20WA"%20within%3A15mi%20since%3A2017-05-02%20until%3A2017-05-05 -o tweets.json`

**Comment by aliyudin21** [comment]
I run the code on Eclipse.
I converted the result to dataframe and stored it on excel

So, where I should put and run the code ?

**Comment by taspinar** [comment]
![running_scraper](https://cloud.githubusercontent.com/assets/4409108/26548016/397a9e2c-4472-11e7-9c42-e53582c44c43.png)

You can run the code from any command line, after twitterscraper has been installed with 'pip install twitterscraper'

**Comment by aliyudin21** [comment]
Ok, thanks for your kindly response @taspinar 

I will close this issue.
