### ISSUE TITLE
More attributes

### ISSUE THREAD

**Issue by ashgreat** [taspinar/twitterscraper#35]
Is it possible to get more attributes like number of retweets, replies, and favorites? This is a feature request I guess

**Comment by taspinar** [comment]
Hi ashgreat,
This will be a very usefull feature and shouldnt be too hard to implement. I hope I can make some time for it this week, or otherwise this weekend.

**Comment by taspinar** [comment]
@ashgreat version 0.3.0 which is now available on PyPi includes the no of retweets, replies, and likes in the output. 
You can upgrade to the latest version with ```pip install --upgrade twitterscraper```

**Comment by ashgreat** [comment]
That's awesome! Thanks, it works perfect
