### ISSUE TITLE
Why Does Not Work? 

### ISSUE THREAD

**Issue by hakanyusufoglu** [taspinar/twitterscraper#354]
What needs to be done for this library to work?  Previously it was corrected with changes.  What needs to be done now?

**Comment by Sami-listens** [comment]
Apparently, twitter scrappers have stopped working due to some #bannedByTwitter. You may check [this](https://github.com/Altimis/Scweet) repo for latest legal twitter scraper.

**Comment by hakanyusufoglu** [comment]
> Apparently, twitter scrappers have stopped working due to some #bannedByTwitter. You may check [this](https://github.com/Altimis/Scweet) repo for latest legal twitter scraper.

Thank you for answer.
