### ISSUE TITLE
Extract tweets using user handler and the problem with  number of retweets and likes?

### ISSUE THREAD

**Issue by pratimaupadhyay02** [taspinar/twitterscraper#36]
Sir
I am getting the data but the number of retweets and likes are always shown as zero. I wonder why is it so! And also I wanted to know if there is a way to extract tweets of a specific person using username?

**Comment by taspinar** [comment]
Hi Pratimau,
Most of the tweets have no retweets, hence the value 0. But if a tweet has a retweet the correct number should be shown.
You can search for a specific author by adding from%3A<AUTHOR> to the query.

**Comment by pratimaupadhyay02** [comment]
Sir
Thankyou for the suggestion
I used the command twitterscraper from%3Anarendramodi --limit 100 --output=modiii.json
I got all the tweets of narendramodi but still the number of retweets,likes and replies show zero, which is not the case, as I verified it from the profile. Please suggest some way if the problem is figured out. Thanks

**Comment by taspinar** [comment]
That is strange, because with the same command I get the correct number of retweets, replies and favs. 
![image](https://user-images.githubusercontent.com/4409108/29265201-62340d30-80e0-11e7-9444-ae18069ea662.png)

Do you have the lastest version installed? (0.3.0)

**Comment by pratimaupadhyay02** [comment]
I didn't have the latest version. I tried upgrading it with the command pip install twitterscraper --upgrade but it seems that it encountered some errors. I am posting the screenshots of the errors here. Also , after that I directly downloaded the zipped folder of 0.3 version from your account and installed it. It installed successfully, but even after that when I tried the command, I still get zero likes,retweets and replies. It's quite strange because when I didn't use from%3A I got the tweets of the general public and in this case I got proper numbers. I tried the date command from the advanced search portion and extracted the tweets of sachin tendulkar, still encountered the same problem of zero likes,retweets and replies. I needed the count of features for an academic project and from all other ways we are getting limited number of tweets and the purpose does not seem to get solved.

**Comment by pratimaupadhyay02** [comment]
![twitter2](https://user-images.githubusercontent.com/22002770/29277229-aa4e81d8-812e-11e7-96b1-a9735e21d8df.png)
![twitterscrapererror](https://user-images.githubusercontent.com/22002770/29277228-aa49d660-812e-11e7-9e71-c70e4ccf4bb7.png)

**Comment by taspinar** [comment]
Hi Pratima,
It is strange you should get errors during the upgrade installation (since the requirements did not change). 

Maybe you can uninstall all installed versions, and install again. At the moment you probably have the two different versions installed and I can not be sure which one you are using.

**Comment by pratimaupadhyay02** [comment]
I wonder if the problem is due the anaconda python installed in my system or so ! I told some of my friends to try on their system and they got the same result :(

**Comment by taspinar** [comment]
This issue should be fixed with PR#49 (version number 0.3.1)
