### ISSUE TITLE
Accessing JSON file with stored tweets

### ISSUE THREAD

**Issue by Sandipatel** [taspinar/twitterscraper#38]
After carrying out the CLi search, how do I access the JSON file which the tweets are stored in?

**Comment by taspinar** [comment]
```
import json
filename = 'output.json'
with open(filename) as inputfile:
    data = json.load(inputfile)
```

(or you can use notepad++)

**Comment by Sandipatel** [comment]
![cp](https://user-images.githubusercontent.com/29729227/29613483-15f8cd46-87fe-11e7-8758-c7ba00d27429.png)

The thing is I have used command prompt to collect the tweets (shown above) so how can i access the JSON file from command prompt? Or where is this file stored?

Thanks in advance

**Comment by aliyudin21** [comment]
Hello @Sandipatel 
Seems you got the same problem with me, but finally I found my .json file. 
There is two ways to find your .json.

1. You can access C:\Users\yourusername, the .json file is stored there.
2. Open command line and type :  dir tweets.json /s /p

Hope it can help you.

**Comment by taspinar** [comment]
Hi all,
In both windows and linux the json file is always stored in the directory from where you have run the CLI.
