### ISSUE TITLE
Inconsistent results among multiple runs

### ISSUE THREAD

**Issue by gianlucascoccia** [taspinar/twitterscraper#40]
I am using twitterscraper to get the replies to some twitter accounts.

I am running the following queries as a test: 
```
to%3Amatteorenzi%20since%3A2017-08-21%20until%3A2017-08-27
to%3Amatteosalvinimi%20since%3A2017-08-21%20until%3A2017-08-27

```

When performing multiple runs I get a different amount of results each time as below, with left number being the result of first query and right one for the second. Each line is a different run.

544, 4216
386, 4121
295, 4180 

Why does this happen? Any way I can prevent it?

**Comment by aliyudin21** [comment]
Have you checked the keyword thorugh https://twitter.com/search-advanced 

Recently I checked there is something wrong with Twitter, because when I run the keyword `Telkomsel`, it doesn't work well. I think your keyword got the same problem from Twitter.

But it can work well if we add another keyword after the main keyword as example : `Amatteorenzi cool`

**Comment by Fragoel2** [comment]
What I am doing is collecting replies to a given twitter user. Given the amount of results (thousands) I can't check by hand what is the correct result. I am going to investigate this further and provide updates if I find some more useful information.

**Comment by taspinar** [comment]
Thank you @Fragoel2 . At the moment I am too busy with work to have a look at it myself.

**Comment by taspinar** [comment]
Hi @Fragoel2 ,
For three runs of the first query, I get the following 1087 tweets at each run. That is, there is no inconsistent run...

With you It seems to be exiting earlier for some reason. Can you find something in the log file or could it have something to do with your internet speed?

**Comment by taspinar** [comment]
With the latest release (> 0.4.0) you should get consistent results among multiple runs. Although the interface has slightly been changed:
twitterscraper "to:matteorenzi" -bd 2017-08-21 -ed 2017-08-27 -o output3.json
twitterscraper "to:matteosalvinimi" -bd 2017-08-21 -ed 2017-08-27 -o output4.json
