### ISSUE TITLE
Zero Result

### ISSUE THREAD

**Issue by aliyudin21** [taspinar/twitterscraper#41]
Hello @taspinar 

Recently I run twitterscraper from my command line. 

`C:\Python27\Scripts\twitterscraper Telkomsel -o tweets.json`

Unfortunately, resulting zero result. But if I add another keyword like `Telkomsel mengecewakan` resulting the tweet related keyword. 

In the other hand, if I write 

`C:\Python27\Scripts\twitterscraper Trump -o tweets.json` it runs very well.

Why it happens ? 

This is weird, I checked Telkomsel on Twitter, sometimes it reloads and sometimes it stucks at all. Is it part of Twitter bug ?

**Comment by taspinar** [comment]
Issue could not be reproduced.
