### ISSUE TITLE
Basic Example/Documentation in Python file

### ISSUE THREAD

**Issue by IljaK91** [taspinar/twitterscraper#45]
Hi there,

It would be great, if there was a basic example that does the following in a Python script:

1. set a query for a specific time
2. save the data on the hard drive

Probably this is just me being new to Python, but a general documentation with a brief description for each functionality would also be nice.

Thanks in advance!

**Comment by taspinar** [comment]
I have added a section to readme.md (see 2.3) describing the usage of twitterscraper from within Python.
