### ISSUE TITLE
Likes, Retweets, Replies not being parsed if (> 999)

### ISSUE THREAD

**Issue by adupuis2** [taspinar/twitterscraper#48]
Tweet data for these fields is not being properly parsed if the values exceed 999.

I suspect that it relates to the fact that Twitter displays those values with letters in them. eg, "1.1k" instead of 1100.

In any case, Twitterscraper returns those values as 0.

**Comment by adupuis2** [comment]
I think I've fixed it -- there's an open pull request with the changes.

**Comment by RaviGill247** [comment]
Thanks for the fix. Seems to be working fine now.

**Comment by muahid12** [comment]
@adupuis2 I tried changing the code in the tweet file ... uninstalled the file and installed again. Still the issues is not going. Please help me with this. Thanks

**Comment by taspinar** [comment]
Merged PR#49.
Thank you for your contirbution!
