### ISSUE TITLE
How to scrape users' tweets 

### ISSUE THREAD

**Issue by almohalwi22** [taspinar/twitterscraper#50]
I'm trying to extract specified users' tweets.
By using this command line: twitterscraper Trump --limit 100 --output=tweets.json

it just extracts all twists that the person name is mentioned in it instead of the users' tweets.

My question, how can extract all specified users' tweets 
Thank you...

**Comment by taspinar** [comment]
Here is in example of how to retrieve tweets from user "ataspinar2":
```
twitterscraper from%3Aataspinar2 -o tweets.json
```
