### ISSUE TITLE
Error: message "Error occurred during getting browser"

### ISSUE THREAD

**Issue by mchevita** [taspinar/twitterscraper#52]
I successfully installed twitterscraper on my notebook, using Linux. But, when I tried to run it, I got the following error message:

"Error occurred during getting browser"

What should I do?

Thanks.

**Comment by AlJohri** [comment]
same issue

```
  File "/Users/johria/.local/share/virtualenvs/twitter-tools-wHDH5D_X/lib/python2.7/site-packages/fake_useragent/fake.py", line 139, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
```

**Comment by leips** [comment]
There was a problem with fake_useragent , especifically in user agent's cache server connection.

Update the version
`pip install -U fake-useragent`

Right now it's working!

**Comment by mchevita** [comment]
Thank you! It is working now. This program will be very useful to my research. Thanks!!! I'll try to make some contributions as soon as possible.

**Comment by taspinar** [comment]
thanks @leips and @mchevita 
Any contribution would be welcome.
