### ISSUE TITLE
Add option to query by language

### ISSUE THREAD

**Issue by sinzin91** [taspinar/twitterscraper#58]
Given that this is just parameter in the Twitter API, it should be easy to do, and frustrating that it isn't already available

**Comment by taspinar** [comment]
Hi sinzini91,
I'll add this feature to twitterscraper as soon as I have time. For now, you can query Tweets written in a specific language by adding "%20lang%3Aen" (for en/english) to the end of the query. For a list of all available languages and their corresponding abbreviations see https://twitter.com/search-advanced

**Comment by taspinar** [comment]
@sinzin91 This issue should be solved with PR #61
