### ISSUE TITLE
Python 3 Rewrite

### ISSUE THREAD

**Issue by sils** [taspinar/twitterscraper#6]
Hi,

I did a python 3 rewrite. It's a bit shorter, only takes about 90 LOC, and has a cleaner API IMO. It supports arbitrary queries and I basically got rid of the IO and a lot of other stateful stuff: https://github.com/sils/twitterscraper/blob/sils/auth/scrape_from_author.py

**Comment by sils** [comment]
PR is submitted #7

**Comment by taspinar** [comment]
PR #7 is approved.
