### ISSUE TITLE
Warning: this package expressly violates Twitter's TOS

### ISSUE THREAD

**Issue by andyreagan** [taspinar/twitterscraper#60]
https://twitter.com/en/tos

"scraping the Services without the prior consent of Twitter is expressly prohibited"

**Comment by mchevita** [comment]
But the web pages are public, aren't they? It's the same of go manually to the page, save it and them extract its content. Or not?

**Comment by andyreagan** [comment]
I'm not a lawyer, but using a program to download the webpage and parse it
sounds like "scraping", which their ToS is clearly intentioned to prohibit.

Including a link to the ToS on a public page has not held up in court for
Twitter to protect their content. This is because using your package does
not require agreeing to that ToS (no signing in), and the link isnt
"sufficient notice." Of course that could go the other way in the future,
and you are IMHO breaking those terms....so you should at least _warn_
users of this potential.

**Comment by andyreagan** [comment]
Closing in light of #272, as long as you're not logging in first...seems like you'll win in court.
