### ISSUE TITLE
Twitter's advanced search will not provide usable OR results with firefox 

### ISSUE THREAD

**Issue by dkennedy778** [taspinar/twitterscraper#67]
This isn't really a twitterscraper issue, but it should be updated on the readme. 

The advanced search method won't provide usable results on the newest version of firefox. For example, the following "the,i,to,a,and" produces the%2C OR i%2C OR to%2C OR a%2C OR and%2C in firefox, which twitterscraper can't understand. With the same input chrome generates "the%2Ci%2Cto%2Ca%2Cand", which works fine. 

Haven't tested out what else breaks in firefox (will update if I have the time), but the readme should be updated to reflect that users should only use chrome to generate queries with advanced search

**Comment by taspinar** [comment]
Thanks for the information @dkennedy778 !
I will update the readme file
