### ISSUE TITLE
"Unrecognized arguments -bd 2017-01-01 -ed 2017-01-06"

### ISSUE THREAD

**Issue by tomtaila** [taspinar/twitterscraper#71]
Using the following example query givees the above error:

twitterscraper Trump -l 100 -bd 2017-01-01 -ed 2017-06-01 -o tweets.json

**Comment by taspinar** [comment]
Could you check which version of twitterscraper you have installed with ```pip show twitterscraper```

**Comment by tomtaila** [comment]
Name: twitterscraper
Version: 0.4.1

**Comment by tomtaila** [comment]
Very strange it's no longer giving that error...
