### ISSUE TITLE
Issue with Tweets before 2017 when running within python

### ISSUE THREAD

**Issue by GreenPirate** [taspinar/twitterscraper#79]
Thanks for the twitterscraper, I hope it will save me a lot of work! 

I have a list of Twitter Accounts and I want to get their Tweets since 2015 (actually its 2010 but for usability and testing let's say 2015 in this example). However I don't get Tweets older than 2017. For example, retrieving the timeline of Tom Hanks manually in the twitter advanced search shows all the tweets since 2015: 
[https://twitter.com/search?f=tweets&q=from%3Atomhanks%20since%3A2015-01-01&src=typd](url)

The Search Term thus should be _from:tomhanks since:2015-01-01_ (as displayed in the search bar), right? 

However, when pasting this into the code below (line 13) the default value of 01.01.2017 seems to overrule that value - I only get tweets from 2017 onwards. 

	
	from twitterscraper import query_tweets
	from twitterscraper.main import JSONEncoder
	import json

	with open('test.txt', 'r') as f:
	handles = f.readlines()

	handles = [h.rstrip('\n') for h in handles]

	all_tweets = {}
	if __name__ == '__main__':
		for handle in handles:
			all_tweets[handle] = query_tweets(f"from:{handle} since:2010-01-01")

		with open('all_tweets.json', 'w') as f:
			json.dump(all_tweets, f, cls=JSONEncoder)

Thanks for your support!

**Comment by taspinar** [comment]
Hi @GreenPirate 
As of version 0.4.1/2 the interface to query_tweets has been changed and the begin/end dates are passed as arguments to the method query_tweets. 
The default values are : `query_tweets(query, limit=None, begindate=dt.date(2017,1,1), enddate=dt.date.today(), poolsize=20, lang='')` 

You can change these default values as you see fit during the function call.

**Comment by GreenPirate** [comment]
Hi @taspinar 
So I definitely wouldn't have figured that out without your help, thanks so far! 

So the adjustment of the code this way leads to no tweet-results: 

	all_tweets[handle] = query_tweets(f"from:{handle}, limit=None, begindate=dt.date(2015,1,1), enddate=dt.date.today(), poolsize=20, lang=''")

While this adjustment leads to an error (I'm using Python 3.6): _NameError: name 'dt' is not defined_

		all_tweets[handle] = query_tweets(f"from:{handle}", limit=None, begindate=dt.date(2015,1,1), enddate=dt.date.today(), poolsize=20, lang='')

So sorry for asking, but where do I need to adapt that default values?

**Comment by taspinar** [comment]
It looks like you need to import the datetime module: `import datetime as dt`

**Comment by GreenPirate** [comment]
It looks like I need some sleep ;) Totally true! 
So the date issue is solved, thank you! 

However I'm still experiencing difficulties with the code. Sometimes I get an error like the one below. It seems so occur almost randomly but somewhat related to the size/amounts. 

Let me give you some examples of Usernames in the text.txt input file (sorry, not representative of my taste in culture!): 
Username tomhanks only: works (~800 Tweets)
Username ladygaga only: works (~8.600 Tweets)
Username _helene_fischer only: works (~350 Tweets)

Usernames ladygaga and tomhanks: error 
Usernames tomhanks and _helene_fischer: works 
Usernames ladygaga and _helene_fischer: error

Do I need to open a new issue since this one is solved? 

This is my error:
_ERROR:root:An unknown error occurred! Returning tweets gathered so far.
Traceback (most recent call last):
  File "C:\...\Programs\Python\Python36\lib\site-packages\twitterscraper\query.py", line 92, in query_tweets_once
    pos is None
  File "C:\...\Programs\Python\Python36\lib\site-packages\twitterscraper\query.py", line 37, in query_single_page
    json_resp = response.json()
  File "C:\...\Programs\Python\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\...\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\...\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\...\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)_

**Comment by GreenPirate** [comment]
Hi @taspinar, do you want me to ope a new issue since this is not related to the date issue? Or do you have any idea where I'm having the mistake? 
Thanks for your support!

**Comment by taspinar** [comment]
With the latest version JSONDecoderError's are catched and the process continues. So hopefully this will no longer be a problem.
