### ISSUE TITLE
UTF-8 self.writer.writerow(post) issue

### ISSUE THREAD

**Issue by raphadasilva** [taspinar/twitterscraper#8]
Hello !

I'm trying to scrap every tweets from an account. My script is quite simple : 

_!/usr/bin/env python
 encoding: utf-8

from twitterscraper import TwitterScraper

topic = ""
cible = "tprincedelamour"
filename = 'tprincedelamour_tweets.csv'
scraper = TwitterScraper.Scraper(topic, 21000, authors=cible, filename = filename)
scraper.scrape()_

It works for hundreds of tweets, but then I've got these error : 

_Traceback (most recent call last):
  File "myscript.py", line 10, in <module>
    scraper.scrape()
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/TwitterScraper.py", line 148, in scrape
    self.write(post)
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/TwitterScraper.py", line 136, in write
    self.writer.writerow(post)_

(Yes, I'm using python 2.7, don't know if the problem came from here or not)

Thanks in advance

**Comment by taspinar** [comment]
Hi raphadasilva,
The error message does not give much to go on, but in any case with the new pull request, csv writer will no longer be used so this part of the code becomes redundant.
