### ISSUE TITLE
what if the output i want into excel csv format instead of json ??

### ISSUE THREAD

**Issue by hemangpar** [taspinar/twitterscraper#80]

**Comment by taspinar** [comment]
At the moment there are no plans to add possibilities for different output formats to twitterscraper. However, there are [various tools](https://www.google.nl/search?q=json+to+csv) available which can convert json to csv.

**Comment by hemangpar** [comment]
Thanks, Buddy. I appreciate the help.

**Comment by taspinar** [comment]
BTW, in the latest version (0.7.0) you can also save the results to a CSV format.
