### ISSUE TITLE
Can't Execute Necessary Location-Based Queries from CL in 4.2 

### ISSUE THREAD

**Issue by midnightdream1** [taspinar/twitterscraper#82]
First, thank you for this tool. My discovery of it inspired my current project.

However. putting the language argument aside for the moment, the current query that gets me the desired result at the Twitter Advanced Search Page is:

near%3A"Incheon%2C%20Republic%20of%20Korea"%20within%3A1mi

BUT the closest I can get is: 

near%3AIncheon%2C%20Republic%20of%20Korea%20within%3A1mi

Which gives me completely different (and inaccurate) results.

As far as I can tell, this is do to the parser not being able to include quotation marks in the query (before "Incheon" and after "Korea" in the query string), which in the case of Korean cities and provinces, are required. Is there any way around this? My current research project entails creating a corpus of tweets for various regions in Korea over different periods of time. Any help would be much appreciated! I am running Twitterscraper 4.2 on Ubuntu 16.04.

**Comment by taspinar** [comment]
@midnightdream1 
Is this still an issue? If it is, did you try to use nested quotes?
`twitterscraper 'near%3A"Incheon%2C%20Republic%20of%20Korea"%20within%3A1mi' -o outputfile.json`
