### ISSUE TITLE
Cannot get all tweets from one user

### ISSUE THREAD

**Issue by ptz3233** [taspinar/twitterscraper#88]
When trying to run a simple query to get all the tweets from one user, I only get about 1/5 of the total tweets I should be getting.

Here's a console printout of what happens:
C:\Users\Peter>twitterscraper "from:NJTRANSIT_MBPJ"
INFO: Got 0 tweets (0 new).
INFO: Got 68 tweets (68 new).
INFO: Got 144 tweets (76 new).
INFO: Got 225 tweets (81 new).
INFO: Got 299 tweets (74 new).
INFO: Got 363 tweets (64 new).
INFO: Got 476 tweets (113 new).
INFO: Got 535 tweets (59 new).
INFO: Got 631 tweets (96 new).
INFO: Got 736 tweets (105 new).
INFO: Got 820 tweets (84 new).
INFO: Got 955 tweets (135 new).
INFO: Got 1038 tweets (83 new).
INFO: Got 1165 tweets (127 new).
INFO: Got 1259 tweets (94 new).
INFO: Got 1367 tweets (108 new).
INFO: Got 1521 tweets (154 new).
INFO: Got 1648 tweets (127 new).
INFO: Got 1765 tweets (117 new).
INFO: Got 1967 tweets (202 new).

It stops here, however this account has 9359 tweets, and I would like to get all of them.

**Comment by ptz3233** [comment]
I was able to fix this issue by increasing the pool size.

**Comment by azukhrufy** [comment]
can i get tweet from user that have protected account ?
