### ISSUE TITLE
except urllib2.HTTPError, e: (invalid syntax)

### ISSUE THREAD

**Issue by raphadasilva** [taspinar/twitterscraper#9]
Hello again !

I've just tried my precedent script in Python 3, and got immediately these error : 

  _File "myscript.py", line 4, in <module>
    from twitterscraper import TwitterScraper
  File "/usr/local/lib/python3.4/dist-packages/twitterscraper/TwitterScraper.py", line 109
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax_

Maybe it's a naive alternative, but I've discovered recently requests and found this module more powerful than urllib. Here some [scraping example](https://github.com/raphadasilva/Scrapers_prix_litteraires/blob/master/scraper_prix_litteraires_france.py) with requests !

**Comment by sils** [comment]
@taspinar might also help making it python 2/3 compatible simpler?

**Comment by taspinar** [comment]
@raphadasilva , @sils 
yes it does look like requests will make it much simpler. 

Let me make a branch from the master

**Comment by taspinar** [comment]
@raphadasilva  @sils 
Could you guys have a look at PR #26

**Comment by sils** [comment]
FWIW we don't use that syntax anymore anyway do we? So is this issue still valid?

**Comment by sils** [comment]
(even without that PR)

**Comment by taspinar** [comment]
issue closed
