### ISSUE TITLE
How can I use a location name with space in between

### ISSUE THREAD

**Issue by rahuldebdas** [taspinar/twitterscraper#94]
Hi I am using a your tool to scrap data. When the location has only one token (Melbourne) it works fine but when it has more than one token (The Netherlands) or (West Bengal) it does not return any results. I tried the following as well but no result (Got 0 tweets for.....). Please let me know how can I solve this issue. TIA.

twitterscraper "near%3A"the%20netherlands"%20within%3A15mi since:2017-12-01 until:2017-12-31" --output=N_Dec_2017.json

**Comment by taspinar** [comment]
You can use a [nested quotation](https://en.wikipedia.org/wiki/Nested_quotation), but the inner quotation has to have different characters than the outer quotation. For example ' for the inner and " for the outer.

**Comment by rahuldebdas** [comment]
Thanks Taspinar. It worked. However I am trying to geocode the user's home location. I used one of the codes given in this forum, however, it seems the code does not work. Can you tell me where should I make a change. The screenshot is attached. 
![user_homelocation_geocoder](https://user-images.githubusercontent.com/13996937/36540571-2c5c12a6-17db-11e8-8509-8db7b68af21d.png)

**Comment by taspinar** [comment]
Hi @rahuldebdas .
It is difficult to say since I can not see what the input data is. All I can say is that the `list_of_users` should literally be a Python list with usernames. So please check if that is the case.
