### ISSUE TITLE
Printing Tweet Through python?

### ISSUE THREAD

**Issue by idelgado2** [taspinar/twitterscraper#97]
I am unable to print the tweet through python, I get the instance of the object and not the actual tweet information. How do I print the actual tweet through python? given example in manual does not work currently. 

ex:  
     from twitterscraper import query_tweets
     
     if __name__ == '__main__':
         for tweet in query_tweets('from:StephenCurry30', 10):
             print(tweet)

output:
      <twitterscraper.tweet.Tweet instance at 0x107962cb0>
      <twitterscraper.tweet.Tweet instance at 0x107962cf8> 
      <twitterscraper.tweet.Tweet instance at 0x107962d40>
      <twitterscraper.tweet.Tweet instance at 0x107962dd0>.............

**Comment by Catherinesdataanalytics** [comment]
Thanks for sharing these code. I save the result as json and have the same problems.
Hope to print these out as information.

**Comment by idelgado2** [comment]
/*Resolved Issue*/
Use ".__dict__" to access the entiriety of the tweet information. Subsequently look at the tag names on this output to get individual tag information such as ".user" and ".text"

 if __name__ == '__main__':
     for tweet in query_tweets('from:StephenCurry30', 10):
         print(tweet.__dict__)  #get all information in tweet

#in this example you could use tweet.user or tweet.text to get specific info.
