### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by cursedcelestial** [taspinar/twitterscraper#99]
while using the jsonbugfix branch this error occurs.
 File "/home/tbanalysis/twitterscraper-master/twitterscraper/query.py", line 39, in query_single_page
    return tweets, "TWEET-{}-{}".format(tweets[-1].id, tweets[0].id)
IndexError: list index out of range

**Comment by taspinar** [comment]
Since that branch did not get implemented, but deleted, I'll close this issue.
